### ISSUE TITLE
Possible to resize image at predict time?

### ISSUE THREAD

**Issue by MLnick** [IBM/MAX-Nucleus-Segmenter#4]
Currently we only support certain image sizes. If a larger image is submitted is it possible to resize to the max option (256x256)? What will be the impact on inference accuracy in this case?

**Comment by feihugis** [comment]
Currently, the code can resize the image, so a larger image can be submitted. The reason that we set the max size (256x256) is that Mask-RCNN model we trained only generate 400 anchors per image regardless of the input image size, where the anchor area will be used as the proposed area for the nucleus detection. That means if the input image is big, the model will still propose only 400 anchors and miss some nuclei objects.

**Comment by feihugis** [comment]
I will close this one. Feel free to re-open it if there are more questions.
